model_config:
    # model
    model_name: 'llama_7b'
    model_dtype: "DataType.FLOAT16"     # mindformers.config uses fp16
    model_cfg_path: '/home/ma-user/work/mindformers/configs/llama2/predict_llama2_7b.yaml'
    # tokenizer
    vocab_size: 32000
    pad_token_id: 0
    end_token: 2
    # input
    model_type: 'dyn'       # seems conflict with `seq_type`!!
    seq_type: 'static'
    seq_length: [4096]
    # output
    max_generate_length: 4096
    # batching
    batching_strategy: 'continuous'  # seems conflict with `*_batch_size`!!
    prefill_batch_size: [1]
    decode_batch_size: [1]
    batch_waiting_time: 0.0
    decode_batch_waiting_time: 0.0
    # page-attn
    page_attention: True
    # misc
    current_index: False                        # deprecated
    backend: 'kbk'                              # 'ge', 'kbk'
    zactivate_len: [512, 1024, 2048, 4096]      # only for 'ge'

serving_config:
    agent_ports: [16002]
    start_device_id: 0
    server_ip: '127.0.0.1'
    server_port: 8835

pa_config:      # page_attention
    num_blocks: 1024
    block_size: 16
    decode_seq_length: 4096

tokenizer:
    type: LlamaTokenizer
    vocab_file: '/home/ma-user/work/checkpoint_download/llama2/tokenizer.model'

basic_inputs:
    type: LlamaBasicInputs

extra_inputs:
    type: LlamaExtraInputs

warmup_inputs:
    type: LlamaWarmupInputs
