services:
  ray-head:
    build:
      context: ./Dockerfiles/
      dockerfile: Dockerfile.ray_set2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8265:8265"
      - "6379:6379" 
      - "10001:10001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_HOME=/usr/local/cuda-11.6
      - PATH=/usr/local/cuda-11.6/bin:${PATH}
      - LD_LIBRARY_PATH=/usr/local/cuda-11.6/lib64:${LD_LIBRARY_PATH}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - PYTHONPATH=/app

    volumes:
      - ./rag_models_cache:/app/.mindnlp/model
      - ./main_app2:/app
    networks:
      - rag_net
    shm_size: '10gb'
    command: ray start --head --port=6379 --dashboard-host=0.0.0.0 --block

  ray-worker:
    build:
      context: ./Dockerfiles/
      dockerfile: Dockerfile.ray_set2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_HOME=/usr/local/cuda-11.6
      - PATH=/usr/local/cuda-11.6/bin:${PATH}
      - LD_LIBRARY_PATH=/usr/local/cuda-11.6/lib64:${LD_LIBRARY_PATH}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - PYTHONPATH=/app
    volumes:
      - ./rag_models_cache:/app/.mindnlp/model
      - ./main_app2:/app
    networks:
      - rag_net
    shm_size: '10gb'
    command: ray start --address=ray-head:6379 --num-gpus=1 --num-cpus=8 --block

  main_app:
    build:
      context: ./Dockerfiles/
      dockerfile: Dockerfile.set2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "7860:7860" 
    volumes:
      - ./main_app2:/app
      - ./rag_models_cache:/app/.mindnlp/model
    environment:
      - RAY_ADDRESS=ray://ray-head:10001
      
      - MINIO_HOST=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MILVUS_HOST=standalone
      - MILVUS_PORT=19530

      - CUDA_HOME=/usr/local/cuda-11.6
      - PATH=/usr/local/cuda-11.6/bin:${PATH}
      - LD_LIBRARY_PATH=/usr/local/cuda-11.6/lib64:${LD_LIBRARY_PATH}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - PYTHONPATH=/app
    depends_on:
      standalone:
        condition: service_healthy
      ray-head: 
        condition: service_started
    networks:
      - rag_net
    shm_size: '10gb'
    command: streamlit run main.py --server.port=7860 --server.address=0.0.0.0 --server.enableCORS=false

# 数据库容器配置

  etcd:
    container_name: rag-etcd
    image: quay.io/coreos/etcd:v3.5.18
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - rag_net

  minio:
    container_name: rag-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./volumes/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - rag_net

  standalone:
    container_name: rag-milvus-standalone
    image: milvusdb/milvus:v2.4.1
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      MINIO_ACCESS_KEY_ID: minioadmin
      MINIO_SECRET_KEY_ID: minioadmin
      MINIO_USE_SSL: "false"
    volumes:
      - ./volumes/milvus:/var/lib/milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      etcd:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    networks:
      - rag_net

networks:
  rag_net:
    name: rag_net
    driver: bridge